##
# ScandiPWA_DirectoryGraphQl
#
# @category    ScandiPWA
# @package     ScandiPWA_DirectoryGraphQl
# @copyright   Copyright 2019 Adobe. All Rights Reserved.
# @copyright   Copyright © Scandiweb, Inc. All rights reserved.
# @copyright   Modifications © Selveq. All rights reserved.
# @license     OSL-3.0 (Open Software License ("OSL") v. 3.0)
# See LICENSE for license details.
##

type Country {
    is_state_required: Boolean @resolver(class: "ScandiPWA\\DirectoryGraphQl\\Model\\Resolver\\Country\\IsStateRequired") @doc(description: "Whether the country requires a region")
}
